// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Test

#include "ui.h"

void ButtonPressed(lv_event_t * e)
{
}
