// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Test

#include "ui.h"

lv_obj_t * uic_channel2Mute;
lv_obj_t * uic_channel1Mute;
lv_obj_t * uic_Channel2Vol;
lv_obj_t * uic_Channel1Vol;
lv_obj_t * uic_Panel1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Channel1 = NULL;
lv_obj_t * ui_Channel1Vol = NULL;
lv_obj_t * ui_Channel2 = NULL;
lv_obj_t * ui_Channel2Vol = NULL;
lv_obj_t * ui_channel1Mute = NULL;
lv_obj_t * ui_channel2Mute = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Channel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Channel1, 135);
    lv_obj_set_height(ui_Channel1, 150);
    lv_obj_set_x(ui_Channel1, -75);
    lv_obj_set_y(ui_Channel1, 0);
    lv_obj_set_align(ui_Channel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Channel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Channel1Vol = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Channel1Vol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Channel1Vol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Channel1Vol, -75);
    lv_obj_set_y(ui_Channel1Vol, -32);
    lv_obj_set_align(ui_Channel1Vol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Channel1Vol, "100%");
    lv_obj_set_style_text_font(ui_Channel1Vol, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Channel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Channel2, 130);
    lv_obj_set_height(ui_Channel2, 150);
    lv_obj_set_x(ui_Channel2, 77);
    lv_obj_set_y(ui_Channel2, 1);
    lv_obj_set_align(ui_Channel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Channel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Channel2Vol = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Channel2Vol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Channel2Vol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Channel2Vol, 76);
    lv_obj_set_y(ui_Channel2Vol, -31);
    lv_obj_set_align(ui_Channel2Vol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Channel2Vol, "100%");
    lv_obj_set_style_text_font(ui_Channel2Vol, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_channel1Mute = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_channel1Mute, 94);
    lv_obj_set_height(ui_channel1Mute, 50);
    lv_obj_set_x(ui_channel1Mute, -74);
    lv_obj_set_y(ui_channel1Mute, 41);
    lv_obj_set_align(ui_channel1Mute, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_channel1Mute, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_channel1Mute, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_channel1Mute, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_channel1Mute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_channel2Mute = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_channel2Mute, 97);
    lv_obj_set_height(ui_channel2Mute, 50);
    lv_obj_set_x(ui_channel2Mute, 76);
    lv_obj_set_y(ui_channel2Mute, 38);
    lv_obj_set_align(ui_channel2Mute, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_channel2Mute, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_channel2Mute, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_channel2Mute, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_channel2Mute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_201544590);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -75);
    lv_obj_set_y(ui_Image2, 42);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 128);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_201544590);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 76);
    lv_obj_set_y(ui_Image1, 38);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 128);

    uic_Panel1 = ui_Channel1;
    uic_Channel1Vol = ui_Channel1Vol;
    uic_Channel2Vol = ui_Channel2Vol;
    uic_channel1Mute = ui_channel1Mute;
    uic_channel2Mute = ui_channel2Mute;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_Panel1 = NULL;
    ui_Channel1 = NULL;
    uic_Channel1Vol = NULL;
    ui_Channel1Vol = NULL;
    ui_Channel2 = NULL;
    uic_Channel2Vol = NULL;
    ui_Channel2Vol = NULL;
    uic_channel1Mute = NULL;
    ui_channel1Mute = NULL;
    uic_channel2Mute = NULL;
    ui_channel2Mute = NULL;
    ui_Image2 = NULL;
    ui_Image1 = NULL;

}
