// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Test

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Channel1;
extern lv_obj_t * ui_Channel1Vol;
extern lv_obj_t * ui_Channel2;
extern lv_obj_t * ui_Channel2Vol;
extern lv_obj_t * ui_channel1Mute;
extern lv_obj_t * ui_channel2Mute;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Panel1;
extern lv_obj_t * uic_Channel1Vol;
extern lv_obj_t * uic_Channel2Vol;
extern lv_obj_t * uic_channel1Mute;
extern lv_obj_t * uic_channel2Mute;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

